# fly.toml app configuration file generated for vortexsync on 2025-06-12T10:53:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vortexsync'
primary_region = 'bos'

[build]
